import { DiagramProject } from './types';

export const ECOMMERCE_PRESET: DiagramProject = {
  id: 'preset-ecommerce',
  name: 'E-Commerce Order & Payment Engine',
  packageName: 'com.store.order',
  classes: [
    {
      id: 'c-customer',
      name: 'Customer',
      stereotype: 'class',
      packageName: 'com.store.order',
      docComment: 'Customer account entity storing user details and order references.',
      attributes: [
        { id: 'a1', name: 'id', type: 'UUID', visibility: 'private', isFinal: true },
        { id: 'a2', name: 'fullName', type: 'String', visibility: 'private' },
        { id: 'a3', name: 'email', type: 'String', visibility: 'private' },
        { id: 'a4', name: 'phoneNumber', type: 'String', visibility: 'protected' },
        { id: 'a5', name: 'loyaltyPoints', type: 'int', visibility: 'private', defaultValue: '0' },
      ],
      methods: [
        {
          id: 'm1',
          name: 'addLoyaltyPoints',
          returnType: 'void',
          visibility: 'public',
          parameters: [{ id: 'p1', name: 'points', type: 'int' }],
          customBody: 'this.loyaltyPoints += points;',
        },
        {
          id: 'm2',
          name: 'verifyEmail',
          returnType: 'boolean',
          visibility: 'public',
          parameters: [],
          customBody: 'return this.email != null && this.email.contains("@");',
        },
      ],
    },
    {
      id: 'c-order',
      name: 'Order',
      stereotype: 'class',
      packageName: 'com.store.order',
      docComment: 'Primary aggregate root representing a customer purchasing transaction.',
      attributes: [
        { id: 'a6', name: 'orderNumber', type: 'String', visibility: 'private', isFinal: true },
        { id: 'a7', name: 'orderDate', type: 'LocalDateTime', visibility: 'private' },
        { id: 'a8', name: 'totalAmount', type: 'BigDecimal', visibility: 'private', defaultValue: 'BigDecimal.ZERO' },
      ],
      methods: [
        {
          id: 'm3',
          name: 'calculateTotal',
          returnType: 'BigDecimal',
          visibility: 'public',
          parameters: [],
          customBody: 'return this.itemsList.stream().map(OrderItem::getSubtotal).reduce(BigDecimal.ZERO, BigDecimal::add);',
        },
        {
          id: 'm4',
          name: 'processPayment',
          returnType: 'boolean',
          visibility: 'public',
          parameters: [{ id: 'p2', name: 'strategy', type: 'PaymentStrategy' }],
          customBody: 'return strategy.pay(this.totalAmount);',
        },
      ],
    },
    {
      id: 'c-order-item',
      name: 'OrderItem',
      stereotype: 'class',
      packageName: 'com.store.order',
      docComment: 'Line item bound to an order via strict composition.',
      attributes: [
        { id: 'a9', name: 'sku', type: 'String', visibility: 'private', isFinal: true },
        { id: 'a10', name: 'productName', type: 'String', visibility: 'private' },
        { id: 'a11', name: 'quantity', type: 'int', visibility: 'private' },
        { id: 'a12', name: 'unitPrice', type: 'BigDecimal', visibility: 'private' },
      ],
      methods: [
        {
          id: 'm5',
          name: 'getSubtotal',
          returnType: 'BigDecimal',
          visibility: 'public',
          parameters: [],
          customBody: 'return this.unitPrice.multiply(BigDecimal.valueOf(this.quantity));',
        },
      ],
    },
    {
      id: 'c-order-status',
      name: 'OrderStatus',
      stereotype: 'enum',
      packageName: 'com.store.order',
      docComment: 'State lifecycle of a submitted customer order.',
      enumValues: ['PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED'],
      attributes: [],
      methods: [],
    },
    {
      id: 'c-payment-strategy',
      name: 'PaymentStrategy',
      stereotype: 'interface',
      packageName: 'com.store.order',
      docComment: 'Strategy interface contract for executing monetary transactions.',
      attributes: [],
      methods: [
        {
          id: 'm6',
          name: 'pay',
          returnType: 'boolean',
          visibility: 'public',
          parameters: [{ id: 'p3', name: 'amount', type: 'BigDecimal' }],
        },
        {
          id: 'm7',
          name: 'getProviderName',
          returnType: 'String',
          visibility: 'public',
          parameters: [],
        },
      ],
    },
    {
      id: 'c-credit-card-payment',
      name: 'CreditCardPayment',
      stereotype: 'class',
      packageName: 'com.store.order',
      docComment: 'Credit card payment gateway adapter.',
      attributes: [
        { id: 'a13', name: 'cardNumberMasked', type: 'String', visibility: 'private' },
        { id: 'a14', name: 'cardHolderName', type: 'String', visibility: 'private' },
        { id: 'a15', name: 'expiryDate', type: 'String', visibility: 'private' },
      ],
      methods: [
        {
          id: 'm8',
          name: 'pay',
          returnType: 'boolean',
          visibility: 'public',
          parameters: [{ id: 'p4', name: 'amount', type: 'BigDecimal' }],
          customBody: 'System.out.println("Processing Credit Card charge: " + amount);\nreturn true;',
        },
        {
          id: 'm9',
          name: 'getProviderName',
          returnType: 'String',
          visibility: 'public',
          parameters: [],
          customBody: 'return "VISA/MasterCard Gateway";',
        },
      ],
    },
  ],
  relationships: [
    {
      id: 'rel-cust-order',
      source: 'c-customer',
      target: 'c-order',
      type: 'association',
      sourceMultiplicity: '1',
      targetMultiplicity: '0..*',
      label: 'places',
      targetRole: 'orders',
    },
    {
      id: 'rel-order-items',
      source: 'c-order',
      target: 'c-order-item',
      type: 'composition',
      sourceMultiplicity: '1',
      targetMultiplicity: '1..*',
      label: 'contains',
      targetRole: 'items',
    },
    {
      id: 'rel-order-status',
      source: 'c-order',
      target: 'c-order-status',
      type: 'association',
      sourceMultiplicity: '*',
      targetMultiplicity: '1',
      label: 'has state',
      targetRole: 'status',
    },
    {
      id: 'rel-cc-payment',
      source: 'c-credit-card-payment',
      target: 'c-payment-strategy',
      type: 'realization',
      label: 'implements',
    },
    {
      id: 'rel-order-payment-dep',
      source: 'c-order',
      target: 'c-payment-strategy',
      type: 'dependency',
      label: 'uses',
    },
  ],
  positions: {
    'c-customer': { x: 50, y: 150 },
    'c-order': { x: 420, y: 150 },
    'c-order-item': { x: 800, y: 150 },
    'c-order-status': { x: 420, y: 550 },
    'c-payment-strategy': { x: 800, y: 480 },
    'c-credit-card-payment': { x: 800, y: 720 },
  },
};

export const OBSERVER_PRESET: DiagramProject = {
  id: 'preset-observer',
  name: 'Observer Design Pattern Architecture',
  packageName: 'com.pattern.observer',
  classes: [
    {
      id: 'c-subject-interface',
      name: 'Subject',
      stereotype: 'interface',
      packageName: 'com.pattern.observer',
      docComment: 'Subject interface specifying observer registration and notification.',
      attributes: [],
      methods: [
        {
          id: 'obs-m1',
          name: 'attach',
          returnType: 'void',
          visibility: 'public',
          parameters: [{ id: 'op1', name: 'observer', type: 'Observer' }],
        },
        {
          id: 'obs-m2',
          name: 'detach',
          returnType: 'void',
          visibility: 'public',
          parameters: [{ id: 'op2', name: 'observer', type: 'Observer' }],
        },
        {
          id: 'obs-m3',
          name: 'notifyObservers',
          returnType: 'void',
          visibility: 'public',
          parameters: [{ id: 'op3', name: 'payload', type: 'String' }],
        },
      ],
    },
    {
      id: 'c-observer-interface',
      name: 'Observer',
      stereotype: 'interface',
      packageName: 'com.pattern.observer',
      docComment: 'Observer subscriber contract receiving real-time event updates.',
      attributes: [],
      methods: [
        {
          id: 'obs-m4',
          name: 'update',
          returnType: 'void',
          visibility: 'public',
          parameters: [{ id: 'op4', name: 'message', type: 'String' }],
        },
      ],
    },
    {
      id: 'c-news-agency',
      name: 'NewsAgency',
      stereotype: 'class',
      packageName: 'com.pattern.observer',
      docComment: 'Concrete subject dispatching breaking news announcements.',
      attributes: [
        { id: 'obs-a1', name: 'agencyName', type: 'String', visibility: 'private' },
        { id: 'obs-a2', name: 'latestNews', type: 'String', visibility: 'private' },
      ],
      methods: [
        {
          id: 'obs-m5',
          name: 'publishNews',
          returnType: 'void',
          visibility: 'public',
          parameters: [{ id: 'op5', name: 'news', type: 'String' }],
          customBody: 'this.latestNews = news;\nnotifyObservers(news);',
        },
      ],
    },
    {
      id: 'c-news-channel',
      name: 'NewsChannel',
      stereotype: 'class',
      packageName: 'com.pattern.observer',
      docComment: 'Concrete observer displaying incoming bulletins.',
      attributes: [
        { id: 'obs-a3', name: 'channelName', type: 'String', visibility: 'private' },
      ],
      methods: [
        {
          id: 'obs-m6',
          name: 'update',
          returnType: 'void',
          visibility: 'public',
          parameters: [{ id: 'op6', name: 'message', type: 'String' }],
          customBody: 'System.out.println("[" + channelName + "] Broadcast: " + message);',
        },
      ],
    },
  ],
  relationships: [
    {
      id: 'rel-obs-subj-impl',
      source: 'c-news-agency',
      target: 'c-subject-interface',
      type: 'realization',
      label: 'implements',
    },
    {
      id: 'rel-obs-chan-impl',
      source: 'c-news-channel',
      target: 'c-observer-interface',
      type: 'realization',
      label: 'implements',
    },
    {
      id: 'rel-subj-obs-agg',
      source: 'c-news-agency',
      target: 'c-observer-interface',
      type: 'aggregation',
      sourceMultiplicity: '1',
      targetMultiplicity: '0..*',
      label: 'subscribers',
      targetRole: 'observers',
    },
  ],
  positions: {
    'c-subject-interface': { x: 80, y: 100 },
    'c-observer-interface': { x: 550, y: 100 },
    'c-news-agency': { x: 80, y: 420 },
    'c-news-channel': { x: 550, y: 420 },
  },
};

export const BLANK_PROJECT: DiagramProject = {
  id: 'preset-blank',
  name: 'New Architecture Project',
  packageName: 'com.myapp.domain',
  classes: [
    {
      id: 'c-initial',
      name: 'ApplicationService',
      stereotype: 'class',
      packageName: 'com.myapp.domain',
      docComment: 'Primary service entry point.',
      attributes: [
        { id: 'init-a1', name: 'serviceId', type: 'UUID', visibility: 'private', isFinal: true },
        { id: 'init-a2', name: 'isActive', type: 'boolean', visibility: 'private', defaultValue: 'true' },
      ],
      methods: [
        {
          id: 'init-m1',
          name: 'execute',
          returnType: 'boolean',
          visibility: 'public',
          parameters: [],
        },
      ],
    },
  ],
  relationships: [],
  positions: {
    'c-initial': { x: 250, y: 180 },
  },
};
